# -*- coding: utf-8 -*-
"""RandomForestClassifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H4My0jZAQ9t84qLZUinSLl1gXEDmxsLf
"""

import vega_datasets
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

iris = vega_datasets.data.iris()

spc = {'setosa': 1, 'versicolor': 2, 'virginica': 3}
iris['spc'] = [spc[r] for r in iris ['species']]
x = iris [['petalLength','petalWidth','sepalLength','sepalWidth']]
y = iris ['spc']

iris.head()

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

print('mengapa random_state = 42 karna angka yang akurat untuk mendaptakan hasil pembandingan yaitu 100% atau 1.0')

len(x_train)

len(x_test)

clf = RandomForestClassifier()
clf.fit(x_train,y_train)

y_pred = clf.predict(x_test)

y_pred

r2_score(y_test, y_pred)

print('perbandingan antara y_test dan y_pred sangat akurat')

print('Muhamad Dendi|','|171011400249|','|07TPLP002|','|UAS KECERDASAN BUATAN|')